# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 18:19
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_reg_conference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_conference',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=10),
        ),
    ]
