# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170606_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_conference',
            name='state',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
    ]
