# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 20:50
from __future__ import unicode_literals

from django.db import migrations
import localflavor.in_.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_reg_conference_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_conference',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reg_conference',
            name='state',
            field=localflavor.in_.models.INStateField(max_length=2),
        ),
    ]
