# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170606_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_conference',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
