# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20170606_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg_conference',
            name='image',
        ),
        migrations.AlterField(
            model_name='reg_conference',
            name='address',
            field=models.CharField(max_length=30),
        ),
    ]
