# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20170606_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_conference',
            name='uploaded_file',
            field=models.FileField(default=None, upload_to='', verbose_name='doc'),
            preserve_default=False,
        ),
    ]
