# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_reg_conference_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_conference',
            name='uploaded_file',
            field=models.FileField(upload_to='doc'),
        ),
    ]
