# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20170607_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_conference',
            name='approve_status',
            field=models.CharField(choices=[('a', 'approved'), ('c', 'cancelled'), ('w', 'weightinglist'), ('y', 'yet to check')], default='y', max_length=1),
        ),
    ]
