# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20170706_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birthplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=75)),
                ('state', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Birthplace')),
            ],
        ),
        migrations.RemoveField(
            model_name='ourusers',
            name='user',
        ),
        migrations.DeleteModel(
            name='ourusers',
        ),
    ]
