# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_author_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='our_profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birthplace',
        ),
        migrations.DeleteModel(
            name='author',
        ),
        migrations.DeleteModel(
            name='Birthplace',
        ),
        migrations.DeleteModel(
            name='book',
        ),
        migrations.DeleteModel(
            name='our_profile',
        ),
        migrations.DeleteModel(
            name='our_user',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
