# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20170712_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='state_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='reg_conference',
            name='uploaded_file',
        ),
    ]
