# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20170712_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_conference',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
