# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20170713_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_conference',
            name='phone_number',
            field=models.IntegerField(max_length=12),
        ),
    ]
