# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20170713_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_conference',
            name='address',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='reg_conference',
            name='company',
            field=models.CharField(max_length=26),
        ),
        migrations.AlterField(
            model_name='reg_conference',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reg_conference',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reg_conference',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
